apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
        - name: passwd-volume
          secret:
            secretName: redis-passwd
      containers:
      - image: brendanburns/journal-server:latest
        imagePullPolicy: IfNotPresent
        name: frontend
        resources:
          requests:
            cpu: "1"
            memory: "500Mi"
          limits:
            cpu: "1"
            memory: "500Mi"
        env:
          - name: JOURNAL_ENTRIES
            valueFrom:
              configMapKeyRef:
                key: journalEntries
                name: frontend-config
        volumeMounts:
          - mountPath: "/etc/redis-passwd"
            name: passwd-volume
            readOnly: true